### ISSUE TITLE
What are allowed to be used in password ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/network.loki.Session#1]
Hi.
Kindly, can you explain what are allowed in setting password for ID in this application ?

It show me warning when I typed a password, said "only letters, numbers & symbols are allowed". But when I reviewed the case, I saw application gave the message when using a letter !!!!

A bug or not, this depend on what allowed excactly & what is not allowed.

To avoid confusion, kindly, give in specific what are NOT allowed to be used in password so that we can see if this issue is a bug or not ...

**Comment by GeopJr** [comment]
> Kindly, can you explain what are allowed in setting password for ID in this application ?

According to this line: https://github.com/loki-project/session-desktop/blob/clearnet/app/password_util.js#L30, the allowed characters are:
- Capital and lowercase Latin characters
- All digits from 0 to 9
- These special characters ``- ! ( ) . _ ` ~ @ # $ % ^ & * + = [ ] { } | < > , ; :  ``

**Comment by Nokia808** [comment]
@GeopJr 
Thank you. I suggest on you to dictate this on Flatpak page of this flatpak:
https://www.flathub.org/apps/details/network.loki.Session
because as you see, not all special characters allowed ...
