### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/network.loki.Session#84]
Changelogs can be displayed on Flathub and within distro app updaters, you just need an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another Flatpak's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by GeopJr** [comment]
Not something that should be handled here to be honest but rather upstream. The updates to this flatpak are created and merged automatically based on the upstream's deb releases (per their wishes). This does not give me enough time to manually add the changelog manually to the metainfo file before an update is merged. Ideally, the metainfo file should be maintained on the upstream repo and included with the package releases, allowing the flatpak to utilize it *but* AFAIK, electron-builder does not make it easy.

As a reminder, this flatpak (& the current metainfo file) is **unofficial** even though some of the session & oxen team has access to it.
